# Generated by Django 4.2.7 on 2026-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_method', models.CharField(default='mock_upi', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='contracts.contract')),
            ],
        ),
        migrations.AddConstraint(
            model_name='escrowledger',
            constraint=models.CheckConstraint(check=models.Q(('locked_amount__gte', 0)), name='locked_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='escrowledger',
            constraint=models.CheckConstraint(check=models.Q(('released_amount__gte', 0)), name='released_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='escrowledger',
            constraint=models.CheckConstraint(check=models.Q(('refunded_amount__gte', 0)), name='refunded_amount_non_negative'),
        ),
    ]
