# Generated by Django 4.2.7 on 2026-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('old_state', models.CharField(blank=True, max_length=50)),
                ('new_state', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payee_email', models.EmailField(blank=True, help_text='Email of payee if not yet registered', max_length=254)),
                ('worker_wallet', models.CharField(blank=True, help_text='Worker EVM wallet address (0x...)', max_length=42)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('funds_locked', 'Funds Locked'), ('work_submitted', 'Work Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('terms', models.JSONField(blank=True, default=dict, help_text='Structured terms from AI parsing')),
                ('risk_score', models.FloatField(default=0.0, help_text='AI-assessed risk score 0-100')),
                ('risk_flags', models.JSONField(blank=True, default=list, help_text='Risk flags from AI')),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Monad transaction hash', max_length=66)),
                ('blockchain_verified', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('current_milestone', models.IntegerField(default=0, help_text='Index of the current active milestone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('link', models.URLField(blank=True, help_text='URL to external work delivery', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contracts.contract')),
            ],
        ),
    ]
