# Generated by Django 4.2.29 on 2026-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='worker_wallet',
            field=models.CharField(blank=True, help_text='Worker EVM wallet address (0x...)', max_length=42),
        ),
    ]
