# Generated by Django 4.2.29 on 2026-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_worker_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_milestone',
            field=models.IntegerField(default=0, help_text='Index of the current active milestone'),
        ),
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.URLField(blank=True, help_text='URL to external work delivery', max_length=2000),
        ),
    ]
